name: inker_studio
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dots_indicator: ^2.1.0
  equatable: ^2.0.3
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_native_splash: ^2.2.3+1
  flutter_svg: ^1.1.1
  flutter_typeahead: ^4.0.0
  flutter_verification_code: ^1.1.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.0
  geolocator: ^8.0.1
  google_maps_flutter: ^2.1.10
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_place: ^0.4.7
  google_sign_in: ^5.3.3
  http: ^0.13.4
  intl_phone_number_input:
    git:
      url: https://github.com/AbdOoSaed/intl_phone_number_input
  json_annotation: ^4.4.0
  jwt_decoder: ^2.0.1
  keyboard_actions: ^4.0.1
  modal_bottom_sheet: ^2.1.0
  path_provider: ^2.0.2
  permission_handler: ^8.3.0
  pinput: ^2.2.11
  places_service: ^0.1.2
  rxdart: ^0.27.4
  shared_preferences: ^2.0.6
  simple_animations: ^4.1.0
  sqflite: ^2.0.0+3
  uuid: ^3.0.6

dev_dependencies:
  analyzer: ^4.2.0 
  build_runner: ^2.0.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  lints: ^1.0.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/onboarding/page_1/
    - assets/onboarding/page_2/
    - assets/onboarding/page_3/
    - assets/icons/
    - assets/icons/bottom_nav/
    - assets/icons/svg/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800

