name: inker_studio
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: ^3.3.0
  dots_indicator: ^3.0.0
  equatable: ^2.0.3
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_device_type: ^0.4.0
  flutter_dotenv: ^5.0.2
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.9
  flutter_typeahead: ^5.2.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.0
  freezed_annotation: ^2.2.0
  geolocator: ^11.1.0
  google_maps_flutter: ^2.2.0
  google_sign_in: ^6.2.1
  http: ^1.1.0 
  intl: ^0.19.0
  intl_phone_number_input: ^0.7.4
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  keyboard_actions: ^4.0.1
  map_launcher: ^3.3.1
  modal_bottom_sheet: ^3.0.0-pre
  path_provider: ^2.0.2
  permission_handler: ^11.3.1
  pinput: ^5.0.0
  shared_preferences: ^2.0.6
  simple_animations: ^5.0.2
  sqflite: ^2.0.0+3
  table_calendar: ^3.0.8
  uuid: ^4.4.0
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  shimmer: ^3.0.0
  firebase_remote_config: ^5.1.5
  firebase_analytics: ^11.3.5


dev_dependencies:
  flutter_native_splash: ^2.4.3
  build_runner: ^2.0.0
  flutter_lints: ^4.0.0
  freezed: ^2.2.0
  intl_utils: ^2.8.7
  json_serializable: ^6.0.0
  patrol: ^3.13.0-dev.3
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/onboarding/page_1/
    - assets/onboarding/page_2/
    - assets/onboarding/page_3/
    - assets/icons/
    - assets/icons/bottom_nav/
    - assets/icons/svg/
    - assets/isologotipo_negative.png
    - assets/isotipo_negative.png
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800

flutter_intl:
  enabled: true # Required. Must be set to true to activate the package. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: es_CL # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false
  localizely: # Optional settings if you use Localizely platform. Read more: https://localizely.com/blog/flutter-localization-step-by-step/?tab=automated-using-flutter-intl
    project_id: # Get it from the https://app.localizely.com/projects page.
    branch: # Get it from the “Branches” page on the Localizely platform, in case branching is enabled and you want to use a non-main branch.
    upload_overwrite: # Set to true if you want to overwrite translations with upload. Default: false
    upload_as_reviewed: # Set to true if you want to mark uploaded translations as reviewed. Default: false
    upload_tag_added: # Optional list of tags to add to new translations with upload (e.g. ['new', 'New translation']). Default: []
    upload_tag_updated: # Optional list of tags to add to updated translations with upload (e.g. ['updated', 'Updated translation']). Default: []
    upload_tag_removed: # Optional list of tags to add to removed translations with upload (e.g. ['removed', 'Removed translation']). Default: []
    download_empty_as: # Set to empty|main|skip, to configure how empty translations should be exported from the Localizely platform. Default: empty
    download_include_tags: # Optional list of tags to be downloaded (e.g. ['include', 'Include key']). If not set, all string keys will be considered for download. Default: []
    download_exclude_tags: # Optional list of tags to be excluded from download (e.g. ['exclude', 'Exclude key']). If not set, all string keys will be considered for download. Default: []
    ota_enabled: # Set to true if you want to use Localizely Over-the-air functionality. Default: false

flutter_native_splash:
  color: "#1F0966"  # Tu color azul (31, 9, 102)
  image: assets/isologotipo_negative.png
  
  # Configuración específica para Android 12+
  android_12:
    image: assets/isotipo_negative.png
    color: "#1F0966"
    icon_background_color: "#1F0966"

  # Asegurarnos que la imagen se muestre correctamente
  android_gravity: center
  ios_content_mode: scaleAspectFit
  web_image_mode: center

  # Para mantener la imagen visible
  fullscreen: false

  patrol:
    app_name: Inker Studio
    android:
      package_name: com.example.inker_studio
    ios:
      bundle_id: com.inkerapp.inker
